### ISSUE TITLE
Image difference using perpetual hashing not working

### ISSUE THREAD

**Issue by Pravesh22** [JohannesBuchner/imagehash#189] opened 2023-04-20 09:47 UTC
computed image difference using perpetual hashing(phash function) but gives 0 difference, even image is different. Was working fine in local machine but didn't work on server Linux VM.

**Comment by JohannesBuchner** [comment] 2023-04-20 09:55
duplicate of several other closed issues, the most helpful one is probably https://github.com/JohannesBuchner/imagehash/issues/134

**Closed by JohannesBuchner** 2023-04-20 09:55 UTC
