### ISSUE TITLE
keep the git tag consitent

### ISSUE THREAD

**Issue by hubutui** [JohannesBuchner/imagehash#131] opened 2021-03-26 00:58 UTC
Hey, would you like to keep the git tag format consistent? say `v${pkgver}` or just `${pkgver}`. It would help me a lot for automatically building pkg for ArchLinux. Thanks.

**Comment by JohannesBuchner** [comment] 2021-03-26 07:33
Yes, it should always be v..., 4.0 is a accidental duplicate of v4.0

**Closed by JohannesBuchner** 2021-03-26 07:33 UTC
